const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const AUTH_REQUEST = "AUTH_REQUEST";
const REGISTER = "REGISTER";
const AUTH_ERROR = "AUTH_ERROR";
const FORGOT_PWD = "FORGOT_PWD";
const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
const CONTACT_ERROR = "CONTACT_ERROR";
const CONTACT_US_SUBMITTED = "CONTACT_US_SUBMITTED";
const CONTACT_US_RESET = "CONTACT_US_RESET";
const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";
const SHOW_ERROR = "SHOW_ERROR";
const CLEAR_ERROR = "CLEAR_ERROR";
const RESET_SUCCESS = "RESET_SUCCESS";
const ROOM_ERROR = "ROOM_ERROR";
const ADDING_NEW_ROOM = "ADDING_NEW_ROOM";
const ADD_NEW_ROOM_COMPLETED = "ADD_NEW_ROOM_COMPLETED";
const FETCHING_ALL_LISTING = "FETCHING_ALL_LISTING";
const FETCHED_ALL_LISTING = "FETCHED_ALL_LISTING";
const FETCHING_LISTING = "FETCHING_LISTING";
const FETCHED_LISTING = "FETCHED_LISTING";
const FETCHING_ROOM_LISTING = "FETCHING_ROOM_LISTING";
const FETCHED_ROOM_LISTING = "FETCHED_ROOM_LISTING";
const FETCHING_ROOMMATE_LISTING = "FETCHING_ROOMMATE_LISTING";
const FETCHED_ROOMMATE_LISTING = "FETCHED_ROOMMATE_LISTING";

export {
  LOGIN,
  LOGOUT,
  REGISTER,
  AUTH_REQUEST,
  AUTH_ERROR,
  FORGOT_PWD,
  CLEAR_AUTH_ERROR,
  CONTACT_ERROR,
  START_LOADING,
  STOP_LOADING,
  SHOW_ERROR,
  CLEAR_ERROR,
  CONTACT_US_RESET,
  CONTACT_US_SUBMITTED,
  ROOM_ERROR,
  ADDING_NEW_ROOM,
  ADD_NEW_ROOM_COMPLETED,
  RESET_SUCCESS,
  FETCHING_LISTING,
  FETCHED_LISTING,
  FETCHING_ALL_LISTING,
  FETCHED_ALL_LISTING,
  FETCHING_ROOM_LISTING,
  FETCHED_ROOM_LISTING,
  FETCHING_ROOMMATE_LISTING,
  FETCHED_ROOMMATE_LISTING,
};
